spring:
  application:
    name: customer-service

logging:
  level:
    com.customer.service.client.ProductClient: DEBUG

---
spring:
  config:
    activate:
      on-profile: "!test"
    import: configserver:http://localhost:8888
